config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #ROTAS DOS RESULTADOS
  get    "/resultados"          => "resultados#index"    ,as: "resultados"
  post   "/resultados"          => "resultados#create"   ,as: ""
  get    "/resultados/:id/edit" => "resultados#edit"     ,as: "edit_resultado"
  get    "/resultados/:id"      => "resultados#show"     ,as: "resultado"
  patch  "/resultados/:id"      => "resultados#update"   ,as: ""
  put    "/resultados/:id"      => "resultados#update"   ,as: ""
  delete "/resultados/:id"      => "resultados#destroy"  ,as: ""
  get '/resultado/segredo' => 'resultados#new', as: 'new_resultado'
  #ROTAS DOS DIARIOS
  get    "/diarios"          => "diarios#index"    ,as: "diarios"
  post   "/diarios"          => "diarios#create"   ,as: ""
  get    "/diarios/:id/edit" => "diarios#edit"     ,as: "edit_diario"
  get    "/diarios/:id"      => "diarios#show"     ,as: "diario"
  patch  "/diarios/:id"      => "diarios#update"   ,as: ""
  put    "/diarios/:id"      => "diarios#update"   ,as: ""
  delete "/diarios/:id"      => "diarios#destroy"  ,as: ""
  get '/diario/novo' => 'diarios#new', as: 'new_diario'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "main#noticias"
  get 'sobre' => 'main#sobre', as: 'main_sobre'
  get 'futebol' => 'sessions#futebol', as: 'sessions_futebol'
  get 'luta' => 'sessions#luta', as: 'sessions_luta'
  get 'volei' => 'sessions#volei', as: 'sessions_volei'
  get 'basquete' => 'sessionspremium#basquete', as: 'sessionspremium_basquete'
  get 'tenis' => 'sessionspremium#tenis', as: 'sessionspremium_tenis'
  get 'resultados' => 'sessionspremium#resultados', as: 'sessionspremium_resultados'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diario.rb
class Diario < ApplicationRecord
end

app/models/resultado.rb
class Resultado < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
      
    end
end

app/controllers/diarios_controller.rb
class DiariosController < ApplicationController
  before_action :set_diario, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /diarios
  # GET /diarios.json
  def index
    @diarios = Diario.all
  end

  # GET /diarios/1
  # GET /diarios/1.json
  def show
  end

  # GET /diarios/new
  def new
    @diario = Diario.new
  end

  # GET /diarios/1/edit
  def edit
  end

  # POST /diarios
  # POST /diarios.json
  def create
    @diario = Diario.new(diario_params)

    respond_to do |format|
      if @diario.save
        format.html { redirect_to @diario, notice: 'Diario was successfully created.' }
        format.json { render :show, status: :created, location: @diario }
      else
        format.html { render :new }
        format.json { render json: @diario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diarios/1
  # PATCH/PUT /diarios/1.json
  def update
    respond_to do |format|
      if @diario.update(diario_params)
        format.html { redirect_to @diario, notice: 'Diario was successfully updated.' }
        format.json { render :show, status: :ok, location: @diario }
      else
        format.html { render :edit }
        format.json { render json: @diario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diarios/1
  # DELETE /diarios/1.json
  def destroy
    @diario.destroy
    respond_to do |format|
      format.html { redirect_to diarios_url, notice: 'Diario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diario
      @diario = Diario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diario_params
      params.require(:diario).permit(:titulo, :corpo)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def noticias
  end

  def sobre
  end
end

app/controllers/resultados_controller.rb
class ResultadosController < ApplicationController
  before_action :set_resultado, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /resultados
  # GET /resultados.json
  def index
    @resultados = Resultado.all
  end

  # GET /resultados/1
  # GET /resultados/1.json
  def show
  end

  # GET /resultados/new
  def new
    @resultado = Resultado.new
  end

  # GET /resultados/1/edit
  def edit
  end

  # POST /resultados
  # POST /resultados.json
  def create
    @resultado = Resultado.new(resultado_params)

    respond_to do |format|
      if @resultado.save
        format.html { redirect_to @resultado, notice: 'Resultado was successfully created.' }
        format.json { render :show, status: :created, location: @resultado }
      else
        format.html { render :new }
        format.json { render json: @resultado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resultados/1
  # PATCH/PUT /resultados/1.json
  def update
    respond_to do |format|
      if @resultado.update(resultado_params)
        format.html { redirect_to @resultado, notice: 'Resultado was successfully updated.' }
        format.json { render :show, status: :ok, location: @resultado }
      else
        format.html { render :edit }
        format.json { render json: @resultado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resultados/1
  # DELETE /resultados/1.json
  def destroy
    @resultado.destroy
    respond_to do |format|
      format.html { redirect_to resultados_url, notice: 'Resultado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resultado
      @resultado = Resultado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resultado_params
      params.require(:resultado).permit(:time1, :gols1, :time2, :gols2)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def futebol
     
  end
  
  def luta
  end
  
  def volei
  end
end

app/controllers/sessionspremium_controller.rb
class SessionspremiumController < ApplicationController
  before_action :authenticate_user!
  def basquete
  end
  
  def tenis
  end
  
  def resultados
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diarios_helper.rb
module DiariosHelper
end

app/helpers/inscritos_helper.rb
module InscritosHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/resultados_helper.rb
module ResultadosHelper
end

app/views/application/index.html.erb
<h1>Home</h1>

app/views/diarios/_form.html.erb
<%= form_with(model: diario, local: true) do |form| %>
  <% if diario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diario.errors.count, "error") %> prohibited this diario from being saved:</h2>

      <ul>
      <% diario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-row">
      <div class="form-group col-md-6">
  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo , :class => "form-control", :required => true %>
  </div>
  </div>
  </div>
<div class="form-row">
      <div class="form-group col-md-6">
  <div class="field">
    <%= form.label :corpo %>
    <%= form.text_area :corpo, :class => "form-control", :rows => 8, :required => true %>
  </div>
</div>
</div>
<div class="form-group col-md-6">
  <div class="actions">
    <%= form.submit :Confirmar, :class => "btn btn-primary"%>
  </div>
</div>
<% end %>

app/views/diarios/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <span class="navbar-brand">
    <%= image_tag("logo.png", :alt => "logo", size: "30x30", :class => "navbar-brand") %>
    Portal do Esporte
  </span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse navbar-nav" id="navbarNavAltMarkup">
      <a class="nav-item nav-link" href="/">Home</a>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sessões
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Futebol', sessions_futebol_path, :class => "dropdown-item nav-item nav-link"%>
          <%= link_to 'Luta', sessions_luta_path, :class => "dropdown-item nav-item nav-link"%>
          <%= link_to 'Volei', sessions_volei_path, :class => "dropdown-item nav-item nav-link"%>
        </div>
      </li>
      
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sessões Premium
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Basquete', sessionspremium_basquete_path, :class => "dropdown-item nav-item nav-link"%>
          <%= link_to 'Tenis', sessionspremium_tenis_path, :class => "dropdown-item nav-item nav-link"%>
          <%= link_to 'Ultimos Resultados', resultados_path, :class => "dropdown-item nav-item nav-link"%>
        </div>
      </li>      
      <%= link_to "Publique sua noticia", new_diario_path, :class => "nav-item nav-link" %>
      <%= link_to "Noticias publicadas", "/diarios", :class => "nav-item nav-link active" %>
      <% end %>

      <%= link_to 'Sobre', main_sobre_path, :class => "nav-item nav-link"%>
      |
      <% if user_signed_in? %>
         <span class="nav-item nav-link" disabled>Logado como: <strong><%= current_user.email %></strong>.</span>
        <%= link_to 'Edite seu perfil', edit_user_registration_path, :class => 'nav-item nav-link'%> 
        <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'nav-item nav-link'  %>
      <% else %>
        <%= link_to "Cadastre-se", new_user_registration_path, :class => 'nav-item nav-link'  %> 
        <%= link_to "Entrar", new_user_session_path, :class => 'nav-item nav-link'  %>
      <% end %>
    </div>
</nav>
<h1 class="featurette-heading col-md-12 display-4" style="text-align: center;margin: 30px 0px;">Noticias Publicadas</h1>
<hr class="featurette-divider">
<% @diarios.each do |diario| %>
  <div class="card">
    <div class="card-body featurette-heading">
      <h5 class="col-md-12 display-4">Titulo</h5>
      <h6 class="col-md-12 "><%= diario.titulo %></h6>
      <h6 class="card-title display-4">Corpo</h6>
      <p class="col-md-6" style="text-align: left;"><%= diario.corpo %></p>
      <%= link_to 'Editar', edit_diario_path(diario) %></td>
      <%= link_to 'Apagar', diario, method: :delete, data: { confirm: 'Você tem certeza?' } %>
    </div>
  </div>
<% end %>  
<br>

<hr class="featurette-divider">
<footer class="container py-5">
  <div class="row">
    <div class="col-6 col-md">
      <h5><a class="footer-col-title" href="/futebol">Futebol</a></h5>
      <%= link_to image_tag("football.png", :alt => "football", :size=> "64x64", :class => "img-link"),"/futebol" %>
    </div>
    <div class="col-6 col-md">
      <h5><a class="footer-col-title" href="/luta">Luta</a></h5>
      <%= link_to image_tag("boxing-glove.png", :alt => "boxing-glove", :size=> "64x64", :class => "img-link"),"/luta" %>
    </div>
    <div class="col-6 col-md">
      <h5><a class="footer-col-title" href="/volei">Vôlei</a></h5>
      <%= link_to image_tag("volleyball.png", :alt => "volleyball", :size=> "64x64", :class => "img-link"),"/volei" %>
    </div>
    <div class="col-6 col-md">
      <h5><a class="footer-col-title" href="/sobre">Sobre</a></h5>
      <%= link_to image_tag("info.png", :alt => "info", :size=> "64x64", :class => "img-link"),"/sobre" %>
    </div>
  </div>
</footer>

app/views/diarios/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <span class="navbar-brand">
    <%= image_tag("logo.png", :alt => "logo", size: "30x30", :class => "navbar-brand") %>
    Portal do Esporte
  </span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse navbar-nav" id="navbarNavAltMarkup">
      <%= link_to 'Home', root_path, :class => "nav-item nav-link"%>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sessões
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Futebol', sessions_futebol_path, :class => "dropdown-item nav-item nav-link"%>
          <%= link_to 'Luta', sessions_luta_path, :class => "dropdown-item nav-item nav-link"%>
          <%= link_to 'Volei', sessions_volei_path, :class => "dropdown-item nav-item nav-link"%>
        </div>
      </li>
      
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sessões Premium
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Basquete', sessionspremium_basquete_path, :class => "dropdown-item nav-item nav-link"%>
          <%= link_to 'Tenis', sessionspremium_tenis_path, :class => "dropdown-item nav-item nav-link"%>
          <%= link_to 'Ultimos Resultados', "/resultados", :class => "dropdown-item nav-item nav-link"%>
        </div>
      </li>
      <%= link_to "Publique sua noticia", new_diario_path, :class => "nav-item nav-link" %>
      <%= link_to "Noticias publicadas", "/diarios", :class => "nav-item nav-link" %>
      <% end %>

      <%= link_to 'Sobre', main_sobre_path, :class => "nav-item nav-link"%>
      |
      <% if user_signed_in? %>
         <span class="nav-item nav-link" disabled>Logado como: <strong><%= current_user.email %></strong>.</span>
        <%= link_to 'Edite seu perfil', edit_user_registration_path, :class => 'nav-item nav-link'%> 
        <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'nav-item nav-link'  %>
      <% else %>
        <%= link_to "Cadastre-se", new_user_registration_path, :class => 'nav-item nav-link'  %> 
        <%= link_to "Entrar", new_user_session_path, :class => 'nav-item nav-link active'  %>
      <% end %>
    </div>
</nav>
<h1 class="featurette-heading col-md-12 display-4" style="text-align: center;margin: 30px 0px;">Criado com sucesso!</h1>
<hr class="featurette-divider">
<p>
  <strong>Titulo:</strong>
  <%= @diario.titulo %>
</p>

<p>
  <strong>Corpo:</strong>
  <%= @diario.corpo %>
</p>

<%= link_to 'Editar', edit_diario_path(@diario) %> |
<%= link_to 'Voltar', diarios_path %>
<footer class="container py-5">
  <div class="row">
    <div class="col-6 col-md">
      <h5><a class="footer-col-title" href="/futebol">Futebol</a></h5>
      <%= link_to image_tag("football.png", :alt => "football", :size=> "64x64", :class => "img-link"),"/futebol" %>
    </div>
    <div class="col-6 col-md">
      <h5><a class="footer-col-title" href="/luta">Luta</a></h5>
      <%= link_to image_tag("boxing-glove.png", :alt => "boxing-glove", :size=> "64x64", :class => "img-link"),"/luta" %>
    </div>
    <div class="col-6 col-md">
      <h5><a class="footer-col-title" href="/volei">Vôlei</a></h5>
      <%= link_to image_tag("volleyball.png", :alt => "volleyball", :size=> "64x64", :class => "img-link"),"/volei" %>
    </div>
    <div class="col-6 col-md">
      <h5><a class="footer-col-title" href="/sobre">Sobre</a></h5>
      <%= link_to image_tag("info.png", :alt => "info", :size=> "64x64", :class => "img-link"),"/sobre" %>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portal do Esporte</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/main/noticias.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <span class="navbar-brand">
    <%= image_tag("logo.png", :alt => "logo", size: "30x30", :class => "navbar-brand") %>
    Portal do Esporte
  </span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse navbar-nav" id="navbarNavAltMarkup">
      <a class="nav-item nav-link active" href="#">Home</a>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sessões
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Futebol', sessions_futebol_path, :class => "dropdown-item nav-item nav-link"%>
          <%= link_to 'Luta', sessions_luta_path, :class => "dropdown-item nav-item nav-link"%>
          <%= link_to 'Volei', sessions_volei_path, :class => "dropdown-item nav-item nav-link"%>
        </div>
      </li>
      
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sessões Premium
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Basquete', sessionspremium_basquete_path, :class => "dropdown-item nav-item nav-link"%>
          <%= link_to 'Tenis', sessionspremium_tenis_path, :class => "dropdown-item nav-item nav-link"%>
          <%= link_to 'Ultimos Resultados', resultados_path, :class => "dropdown-item nav-item nav-link"%>
        </div>
      </li>      
      <%= link_to "Publique sua noticia", new_diario_path, :class => "nav-item nav-link" %>
      <%= link_to "Noticias publicadas", diarios_path, :class => "nav-item nav-link" %>
      <% end %>

      <%= link_to 'Sobre', main_sobre_path, :class => "nav-item nav-link"%>
      |
      <% if user_signed_in? %>
         <span class="nav-item nav-link" disabled>Logado como: <strong><%= current_user.email %></strong>.</span>
        <%= link_to 'Edite seu perfil', edit_user_registration_path, :class => 'nav-item nav-link'%> 
        <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'nav-item nav-link'  %>
      <% else %>
        <%= link_to "Cadastre-se", new_user_registration_path, :class => 'nav-item nav-link'  %> 
        <%= link_to "Entrar", new_user_session_path, :class => 'nav-item nav-link'  %>
      <% end %>
    </div>
</nav>
<h1 class="featurette-heading col-md-12 display-4" style="text-align: center;margin: 30px 0px;">Notícias</h1>
<hr class="featurette-divider">
<div class="card-deck">
  <div class="card">
    <%= link_to image_tag("futebol.jpg", :alt => "Santos avança e oferece 2 anos de contrato a Abel, mas Fla segue na briga", :size => "408.33x200", :class => "img-card"),"/futebol" %>  
    <div class="card-body">
      <h5 class="card-title">Santos avança e oferece 2 anos de contrato a Abel, mas Fla segue na briga</h5>
      <p class="card-text">Após duas reuniões com o estafe do técnico Abel Braga, o presidente do Santos, José Carlos Peres, voltou animado do Rio de Janeiro. Segundo apurou o UOL Esporte, o clube paulista avançou nas negociações e já discute tempo de contrato e multa rescisória.</p>
        <%= button_to "Leia mais", sessions_futebol_path, :class => "btn btn-dark center", :method => :get %>
    </div>
  </div>
  <div class="card">
    <%= link_to image_tag("volei.jpg", :alt => "Poderosos, Zenit dá vexame e Sada vira coadjuvante no Mundial", :size=> "408.33x200", :class => "img-card"),"/volei" %>
    <div class="card-body">
      <h5 class="card-title">Poderosos, Zenit dá vexame e Sada vira coadjuvante no Mundial</h5>
      <p class="card-text">Duas quedas monumentais e surpreendentes marcaram esta 14ª edição do Campeonato Mundial de Clubes de vôlei masculino, que está sendo realizado na Polônia: o brasileiro Sada Cruzeiro e o russo Zenit Kazan, gigantes da modalidade, caíram ainda na primeira fase, somando duas derrotas cada um. Sim, as mesmas equipes que há dois anos fizeram a final da competição, com o clube de Belo Horizonte se sagrando tricampeão. Nesta edição, no entanto, desclassificados precocemente, os dois times entraram em quadra nesta quinta-feira (29) apenas para cumprir tabela e tentar se despedir do torneio de maneira honrosa.</p>
      <%= button_to "Leia mais", sessions_volei_path, :class => "btn btn-dark center", :method => :get %>
    </div>
  </div>
  <div class="card">
    <%= link_to image_tag("luta.jpg", :alt => "Anderson Silva", :size => "408.33x200", :class => "img-card"),"/luta" %>
    <div class="card-body">
      <h5 class="card-title">Anderson Silva revela promessa de luta por cinturão do UFC em caso de vitória</h5>
      <p class="card-text">Anderson Silva tem 43 anos e está há quase dois sem lutar. No entanto, sua história e seus feitos parecem colocá-lo a uma luta de disputar o cinturão dos pesos-médios (84 kg) novamente. De acordo com o 'Spider', o UFC prometeu um 'title shot' caso ele vença Israel Adesanya no UFC 234, no dia 9 de fevereiro de 2019, em Melbourne (AUS).</p>
      <%= button_to "Leia mais", sessions_luta_path, :class => "btn btn-dark center", :method => :get %>
    </div>
  </div>
</div>
<br>
<hr class="featurette-divider">
<footer class="container py-5">
  <div class="row">
    <div class="col-6 col-md">
      <h5><a class="footer-col-title" href="/futebol">Futebol</a></h5>
      <%= link_to image_tag("football.png", :alt => "football", :size=> "64x64", :class => "img-link"),"/futebol" %>
    </div>
    <div class="col-6 col-md">
      <h5><a class="footer-col-title" href="/luta">Luta</a></h5>
      <%= link_to image_tag("boxing-glove.png", :alt => "boxing-glove", :size=> "64x64", :class => "img-link"),"/luta" %>
    </div>
    <div class="col-6 col-md">
      <h5><a class="footer-col-title" href="/volei">Vôlei</a></h5>
      <%= link_to image_tag("volleyball.png", :alt => "volleyball", :size=> "64x64", :class => "img-link"),"/volei" %>
    </div>
    <div class="col-6 col-md">
      <h5><a class="footer-col-title" href="/sobre">Sobre</a></h5>
      <%= link_to image_tag("info.png", :alt => "info", :size=> "64x64", :class => "img-link"),"/sobre" %>
    </div>
  </div>
</footer>
   

app/views/resultados/_form.html.erb
<%= form_with(model: resultado, local: true) do |form| %>
  <% if resultado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resultado.errors.count, "error") %> prohibited this resultado from being saved:</h2>

      <ul>
      <% resultado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :time1 %>
    <%= form.text_field :time1 %>
  </div>

  <div class="field">
    <%= form.label :gols1 %>
    <%= form.number_field :gols1 %>
  </div>

  <div class="field">
    <%= form.label :time2 %>
    <%= form.text_field :time2 %>
  </div>

  <div class="field">
    <%= form.label :gols2 %>
    <%= form.number_field :gols2 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resultados/edit.html.erb
<h1>Editing Resultado</h1>

<%= render 'form', resultado: @resultado %>

<%= link_to 'Show', @resultado %> |
<%= link_to 'Back', resultados_path %>

app/views/resultados/new.html.erb
<h1>New Resultado</h1>

<%= render 'form', resultado: @resultado %>

<%= link_to 'Back', resultados_path %>

app/views/resultados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time1:</strong>
  <%= @resultado.time1 %>
</p>

<p>
  <strong>Gols1:</strong>
  <%= @resultado.gols1 %>
</p>

<p>
  <strong>Time2:</strong>
  <%= @resultado.time2 %>
</p>

<p>
  <strong>Gols2:</strong>
  <%= @resultado.gols2 %>
</p>

<%= link_to 'Edit', edit_resultado_path(@resultado) %> |
<%= link_to 'Back', resultados_path %>